#!/usr/bin/env perl
use strict;
use warnings;
use Getopt::Std;
use File::Basename;
use File::Spec;
use IO::Uncompress::AnyUncompress;
use Data::Dumper;

#......................................................................................

our $VERSION = "0.0.2";
our $EXE = basename($0);
our $URL = "https://github.com/tseemann/$EXE";

my $DEVNULL = File::Spec->devnull();

#my %FE = (
#  'fastq' => m/\.f(ast)?q(\.gz)?$/,
#  'fasta' => m/\.(fa|fna|fasta)(\.gz)?$/,
#);

my @INFMT = qw'ILL ONT ASM';
my %INFMT = map { ($_ => 1) } @INFMT;

my @OUTFMT = qw'snippy-ng snippy bohra2 bohra json';
my %OUTFMT = map { ($_ => 1) } @OUTFMT;

# default command line options
my %opt = (
 'd' => 4,
 'f' => join(",", @INFMT),
 'F' => $OUTFMT[0],
);

#......................................................................................

sub usage {
  my($errcode) = @_;
  $errcode ||= 0;
  my $ofh = $errcode ? \*STDERR : \*STDOUT;
  print $ofh 
    "NAME\n  $EXE $VERSION\n",
    "SYNOPSIS\n  Scan and organize sequence files\n",
    "USAGE\n  $EXE [opts] file(s) folder(s) > output.tsv\n",
    "OPTIONS\n",
    "  -h       Print this help\n",
    "  -v       Print version and exit\n",
    "  -q       No output while running, only errors\n",
    "  -c       Show citation and exit\n",
    "PARAMETERS\n",
    "  -d INT   Maximum depth to recurse [$opt{d}]\n",
    "  -f CSV   Include filetypes [$opt{f}] from {@INFMT}\n",
    "  -F STR   Output format [$opt{F}] from {@OUTFMT}\n",
    "HOMEPAGE\n  $URL\n",
    "END\n";
  exit($errcode);
}

sub version {
  print "$EXE $VERSION\n";
  exit(0);
}

sub citation {
  print<<"EOC";
If you use this work please cite:

Seemann T. "$EXE" (2025) $URL
EOC
  exit(0);
}

#......................................................................................

sub msg {
  print STDERR "@_\n" unless $opt{q};
}

sub err {
  print STDERR "ERROR: @_\n";
  exit(-1);
}

#......................................................................................

getopts('vhqcD:F:f:', \%opt) or exit(-1);
$opt{v} and version();
$opt{h} and usage(0);
$opt{c} and citation();
@ARGV or err("Please provide some files(s) and/or folder(s)");

#......................................................................................

sub find_pairs {
  my($fns) = @_;
  for my $f (sort keys %$fns) {
    my(undef,$dir,$name) = File::Spec->splitpath($f);
    msg("Pairing: $name");
    if ($name =~ m/_[Rr]1\./) {
      msg("Check for R2 mate?");
    }
  }
}

#......................................................................................

sub seq_type {
  my($fn) = @_;
  $fn or err("seq_type: no file provided");
  msg("Checking: $fn");
  # skip empty files
  return if -s $fn <= 0;
  # read first line to see if we have any data
  my $unzip = IO::Uncompress::AnyUncompress->new($fn);
  return unless $unzip;
  my $line = scalar(<$unzip>); # read first line
  return unless $line;
  if ($line =~ m/^>/) {
    return 'ASM';
  }
  elsif ($line =~ m/^@(\S+)/) {
    my $id = $1;
    # ONT 2019
    # @cd733afc-99bc-4eed-97e4-5abf1852f3b8 runid=38b9f2156c7de329e50c12b2a174b1c25b5b9382 read=1324 ch=8 start_time=2019-12-02T05:37:41Z flow_cell_id=FAK88669 protocol_group_id=M2019-02375 sample_id=M2019-02375 barcode=barcode01
    # ILL 2025 NextSeq500
    # @NS500345:722:HCVVYAFXC:1:11101:24986:1052 2:N:0:69
    return 'ONT' if $id =~ m/^\w+-\w+|\w+=\w+/;
    return 'ILL';
  }
  return; 
}

#......................................................................................

msg("This is $EXE $VERSION");

my @file;
for my $fname (@ARGV) {
  msg("Searching: '$fname'");
  if (-r $fname) {
    my @f = qx"find '$fname' -maxdepth $opt{d} -type f -print 2> $DEVNULL";
    chomp @f;
    push @file, @f;
  }
}

msg("Found", 0+@file, "files");
#print Dumper(\@file);
msg("Analyzing files....");
my %file;
for my $fn (@file) {
  if (my $type = seq_type($fn)) {
    $file{$fn} = $type;
  }
}
msg("Identified", scalar keys %file, "sequence files");
#print Dumper(\%file);
find_pairs(\%file);

msg("Done.");
exit(0);

#......................................................................................

